[build]
  command = "npm run build"
  publish = "build" # or "dist" depending on your build output directory

[build.environment]
  PYTHON_VERSION = "3.8.20"
  NODE_VERSION = "16" # or whatever Node version you're using

[[plugins]]
  package = "@netlify/plugin-python" 