[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.8.10"
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-python"

[[plugins]]
  package = "@netlify/plugin-nextjs"